// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutpageDocumentDataSlicesSlice =
  | ExecutivesSlice
  | HistorySlice
  | ImpactSlice
  | AboutHeroSlice;

/**
 * Content for AboutPage documents
 */
interface AboutpageDocumentData {
  /**
   * Slice Zone field in *AboutPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutpageDocumentDataSlicesSlice> /**
   * Meta Title field in *AboutPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: aboutpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *AboutPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: aboutpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *AboutPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * AboutPage document from Prismic
 *
 * - **API ID**: `aboutpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutpageDocumentData>,
    "aboutpage",
    Lang
  >;

type CoalisionDocumentDataSlicesSlice = CoalisionHeroSlice;

/**
 * Content for Coalision documents
 */
interface CoalisionDocumentData {
  /**
   * Slice Zone field in *Coalision*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CoalisionDocumentDataSlicesSlice> /**
   * Meta Title field in *Coalision*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: coalision.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Coalision*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: coalision.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Coalision*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Coalision document from Prismic
 *
 * - **API ID**: `coalision`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoalisionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CoalisionDocumentData>,
    "coalision",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | SummitHighlightSlice
  | MagnifyOurVoicesSlice
  | HowWeWorkSlice
  | ImpactSlice
  | HomePageAboutSlice
  | HomePageHeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | AboutpageDocument
  | CoalisionDocument
  | HomepageDocument;

/**
 * Primary content in *AboutHero → Default → Primary*
 */
export interface AboutHeroSliceDefaultPrimary {
  /**
   * page header field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.page_header
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_header: prismic.RichTextField;

  /**
   * sub title field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_title: prismic.RichTextField;

  /**
   * title field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * text field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * mission field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.mission
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  mission: prismic.RichTextField;

  /**
   * vission field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.vission
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  vission: prismic.RichTextField;

  /**
   * mandate field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.mandate
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  mandate: prismic.RichTextField;

  /**
   * philosophy field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.philosophy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  philosophy: prismic.RichTextField;

  /**
   * text 2 title field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.text_2_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_2_title: prismic.RichTextField;

  /**
   * text 2 field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.text_2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text_2: prismic.RichTextField;

  /**
   * image1 field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image3: prismic.ImageField<never>;
}

/**
 * Default variation for AboutHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutHero*
 */
type AboutHeroSliceVariation = AboutHeroSliceDefault;

/**
 * AboutHero Shared Slice
 *
 * - **API ID**: `about_hero`
 * - **Description**: AboutHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutHeroSlice = prismic.SharedSlice<
  "about_hero",
  AboutHeroSliceVariation
>;

/**
 * Primary content in *CoalisionHero → Default → Primary*
 */
export interface CoalisionHeroSliceDefaultPrimary {
  /**
   * title field in *CoalisionHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * sub title field in *CoalisionHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision_hero.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_title: prismic.RichTextField;

  /**
   * text field in *CoalisionHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision_hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * image1 field in *CoalisionHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision_hero.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *CoalisionHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision_hero.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *CoalisionHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision_hero.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image3: prismic.ImageField<never>;

  /**
   * image4 field in *CoalisionHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coalision_hero.default.primary.image4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image4: prismic.ImageField<never>;
}

/**
 * Default variation for CoalisionHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoalisionHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoalisionHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoalisionHero*
 */
type CoalisionHeroSliceVariation = CoalisionHeroSliceDefault;

/**
 * CoalisionHero Shared Slice
 *
 * - **API ID**: `coalision_hero`
 * - **Description**: CoalisionHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoalisionHeroSlice = prismic.SharedSlice<
  "coalision_hero",
  CoalisionHeroSliceVariation
>;

/**
 * Item in *Teams → Default → Primary → excutives*
 */
export interface ExecutivesSliceDefaultPrimaryItemsItem {
  /**
   * image field in *Teams → Default → Primary → excutives*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *Teams → Default → Primary → excutives*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * title field in *Teams → Default → Primary → excutives*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Item in *Teams → Default → Primary → country reps*
 */
export interface ExecutivesSliceDefaultPrimaryCountryRepsItem {
  /**
   * image field in *Teams → Default → Primary → country reps*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.country_reps[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *Teams → Default → Primary → country reps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.country_reps[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * title field in *Teams → Default → Primary → country reps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.country_reps[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Item in *Teams → Default → Primary → state reps*
 */
export interface ExecutivesSliceDefaultPrimaryStateRepsItem {
  /**
   * image field in *Teams → Default → Primary → state reps*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.state_reps[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *Teams → Default → Primary → state reps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.state_reps[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * title field in *Teams → Default → Primary → state reps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.state_reps[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Teams → Default → Primary*
 */
export interface ExecutivesSliceDefaultPrimary {
  /**
   * title field in *Teams → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * sub title field in *Teams → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_title: prismic.RichTextField;

  /**
   * excutives field in *Teams → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<ExecutivesSliceDefaultPrimaryItemsItem>>;

  /**
   * country reps field in *Teams → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.country_reps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  country_reps: prismic.GroupField<
    Simplify<ExecutivesSliceDefaultPrimaryCountryRepsItem>
  >;

  /**
   * state reps field in *Teams → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.state_reps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  state_reps: prismic.GroupField<
    Simplify<ExecutivesSliceDefaultPrimaryStateRepsItem>
  >;
}

/**
 * Default variation for Teams Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExecutivesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExecutivesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Teams*
 */
type ExecutivesSliceVariation = ExecutivesSliceDefault;

/**
 * Teams Shared Slice
 *
 * - **API ID**: `executives`
 * - **Description**: Executives
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExecutivesSlice = prismic.SharedSlice<
  "executives",
  ExecutivesSliceVariation
>;

/**
 * Item in *History → Default → Primary → items*
 */
export interface HistorySliceDefaultPrimaryItemsItem {
  /**
   * item title field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * item text field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].item_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_text: prismic.RichTextField;

  /**
   * image field in *History → Default → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * year1 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].year1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  year1: prismic.RichTextField;

  /**
   * month1 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].month1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  month1: prismic.RichTextField;

  /**
   * title1 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].title1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title1: prismic.RichTextField;

  /**
   * text1 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].text1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text1: prismic.RichTextField;

  /**
   * year2 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].year2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  year2: prismic.RichTextField;

  /**
   * month2 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].month2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  month2: prismic.RichTextField;

  /**
   * title2 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].title2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title2: prismic.RichTextField;

  /**
   * text2 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].text2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text2: prismic.RichTextField;

  /**
   * year3 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].year3
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  year3: prismic.RichTextField;

  /**
   * month3 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].month3
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  month3: prismic.RichTextField;

  /**
   * title3 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].title3
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title3: prismic.RichTextField;

  /**
   * text3 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].text3
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text3: prismic.RichTextField;

  /**
   * year4 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].year4
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  year4: prismic.RichTextField;

  /**
   * month4 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].month4
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  month4: prismic.RichTextField;

  /**
   * title4 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].title4
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title4: prismic.RichTextField;

  /**
   * text4 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].text4
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text4: prismic.RichTextField;

  /**
   * year5 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].year5
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  year5: prismic.RichTextField;

  /**
   * month5 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].month5
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  month5: prismic.RichTextField;

  /**
   * title5 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].title5
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title5: prismic.RichTextField;

  /**
   * text5 field in *History → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[].text5
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text5: prismic.RichTextField;
}

/**
 * Primary content in *History → Default → Primary*
 */
export interface HistorySliceDefaultPrimary {
  /**
   * title field in *History → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * items field in *History → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<HistorySliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for History Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HistorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HistorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *History*
 */
type HistorySliceVariation = HistorySliceDefault;

/**
 * History Shared Slice
 *
 * - **API ID**: `history`
 * - **Description**: History
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HistorySlice = prismic.SharedSlice<
  "history",
  HistorySliceVariation
>;

/**
 * Primary content in *HomePageAbout → Default → Primary*
 */
export interface HomePageAboutSliceDefaultPrimary {
  /**
   * image field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * text field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * header text field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.header_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  header_text: prismic.RichTextField;

  /**
   * see more field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.see_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  see_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HomePageAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomePageAboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomePageAbout*
 */
type HomePageAboutSliceVariation = HomePageAboutSliceDefault;

/**
 * HomePageAbout Shared Slice
 *
 * - **API ID**: `home_page_about`
 * - **Description**: HomePageAbout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageAboutSlice = prismic.SharedSlice<
  "home_page_about",
  HomePageAboutSliceVariation
>;

/**
 * Primary content in *HomePageHero → Default → Primary*
 */
export interface HomePageHeroSliceDefaultPrimary {
  /**
   * theme field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Theme
   * - **API ID Path**: home_page_hero.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  theme: prismic.KeyTextField;

  /**
   * hero text field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: From Representation To Protection
   * - **API ID Path**: home_page_hero.default.primary.hero_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_text: prismic.RichTextField;

  /**
   * primary button field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Register for Event
   * - **API ID Path**: home_page_hero.default.primary.primary_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * secondary burron field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Become an Event Partner
   * - **API ID Path**: home_page_hero.default.primary.secondary_burron
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_burron: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * tertiary button field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Find Out More
   * - **API ID Path**: home_page_hero.default.primary.tertiary_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  tertiary_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * hero image field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * sub image 1 field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.sub_image_1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sub_image_1: prismic.ImageField<never>;

  /**
   * sub image 2 field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.sub_image_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sub_image_2: prismic.ImageField<never>;

  /**
   * even and campaign field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.even_and_campaign
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  even_and_campaign: prismic.RichTextField;

  /**
   * policy advocay field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.policy_advocay
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  policy_advocay: prismic.RichTextField;
}

/**
 * Default variation for HomePageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomePageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomePageHero*
 */
type HomePageHeroSliceVariation = HomePageHeroSliceDefault;

/**
 * HomePageHero Shared Slice
 *
 * - **API ID**: `home_page_hero`
 * - **Description**: HomePageHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageHeroSlice = prismic.SharedSlice<
  "home_page_hero",
  HomePageHeroSliceVariation
>;

/**
 * Primary content in *HowWeWork → Default → Primary*
 */
export interface HowWeWorkSliceDefaultPrimary {
  /**
   * title field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * image1 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image3: prismic.ImageField<never>;

  /**
   * image4 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image4: prismic.ImageField<never>;

  /**
   * image5 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image5
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image5: prismic.ImageField<never>;

  /**
   * image1 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image1_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image1_text: prismic.KeyTextField;

  /**
   * image2 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image2_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image2_text: prismic.KeyTextField;

  /**
   * image3 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image3_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image3_text: prismic.KeyTextField;

  /**
   * image4 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image4_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image4_text: prismic.KeyTextField;

  /**
   * image5 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image5_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image5_text: prismic.KeyTextField;
}

/**
 * Default variation for HowWeWork Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HowWeWorkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowWeWorkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HowWeWork*
 */
type HowWeWorkSliceVariation = HowWeWorkSliceDefault;

/**
 * HowWeWork Shared Slice
 *
 * - **API ID**: `how_we_work`
 * - **Description**: HowWeWork
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HowWeWorkSlice = prismic.SharedSlice<
  "how_we_work",
  HowWeWorkSliceVariation
>;

/**
 * Primary content in *Impact → Default → Primary*
 */
export interface ImpactSliceDefaultPrimary {
  /**
   * title field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * productivity text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.productivity_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  productivity_text: prismic.RichTextField;

  /**
   * productivity vlaue field in *Impact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.productivity_vlaue
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  productivity_vlaue: prismic.NumberField;

  /**
   * investment text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.investment_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  investment_text: prismic.RichTextField;

  /**
   * investement value field in *Impact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.investement_value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  investement_value: prismic.NumberField;

  /**
   * customer text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.customer_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  customer_text: prismic.RichTextField;

  /**
   * customer value field in *Impact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.customer_value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  customer_value: prismic.NumberField;

  /**
   * review text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.review_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review_text: prismic.RichTextField;

  /**
   * review value field in *Impact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.review_value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  review_value: prismic.NumberField;
}

/**
 * Default variation for Impact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImpactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Impact*
 */
type ImpactSliceVariation = ImpactSliceDefault;

/**
 * Impact Shared Slice
 *
 * - **API ID**: `impact`
 * - **Description**: Impact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactSlice = prismic.SharedSlice<"impact", ImpactSliceVariation>;

/**
 * Primary content in *MagnifyOurVoices → Default → Primary*
 */
export interface MagnifyOurVoicesSliceDefaultPrimary {
  /**
   * title field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * text field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button1 field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.button1
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button1: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button2 field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.button2
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button2: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button3 field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.button3
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button3: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * logo1 field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.logo1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo1: prismic.ImageField<never>;

  /**
   * logo2 field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.logo2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo2: prismic.ImageField<never>;

  /**
   * logo3 field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.logo3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo3: prismic.ImageField<never>;

  /**
   * logo4 field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.logo4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo4: prismic.ImageField<never>;

  /**
   * logo5 field in *MagnifyOurVoices → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: magnify_our_voices.default.primary.logo5
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo5: prismic.ImageField<never>;
}

/**
 * Default variation for MagnifyOurVoices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MagnifyOurVoicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MagnifyOurVoicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MagnifyOurVoices*
 */
type MagnifyOurVoicesSliceVariation = MagnifyOurVoicesSliceDefault;

/**
 * MagnifyOurVoices Shared Slice
 *
 * - **API ID**: `magnify_our_voices`
 * - **Description**: MagnifyOurVoices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MagnifyOurVoicesSlice = prismic.SharedSlice<
  "magnify_our_voices",
  MagnifyOurVoicesSliceVariation
>;

/**
 * Primary content in *PageHeader → Default → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * wca logo field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.wca_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  wca_logo: prismic.ImageField<never>;

  /**
   * text field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: WCA SUMMIT OCTOBER 2025 (KIGALI, RWANDA)
   * - **API ID Path**: page_header.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * hours field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 22
   * - **API ID Path**: page_header.default.primary.hours
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hours: prismic.NumberField;

  /**
   * minute field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 59
   * - **API ID Path**: page_header.default.primary.minute
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  minute: prismic.NumberField;

  /**
   * seconds field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 22
   * - **API ID Path**: page_header.default.primary.seconds_value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  seconds_value: prismic.NumberField;

  /**
   * days field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 56
   * - **API ID Path**: page_header.default.primary.days
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  days: prismic.NumberField;
}

/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHeader*
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;

/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

/**
 * Item in *SummitHighlight → Default → Primary → item*
 */
export interface SummitHighlightSliceDefaultPrimaryItemItem {
  /**
   * post title field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].post_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  post_title: prismic.RichTextField;

  /**
   * post description field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].post_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  post_description: prismic.RichTextField;

  /**
   * see all field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].see_all
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  see_all: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * image1 field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].image1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].image2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].image3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image3: prismic.ImageField<never>;

  /**
   * image4 field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].image4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image4: prismic.ImageField<never>;

  /**
   * image5 field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].image5
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image5: prismic.ImageField<never>;

  /**
   * image6 field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].image6
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image6: prismic.ImageField<never>;

  /**
   * image7 field in *SummitHighlight → Default → Primary → item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[].image7
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image7: prismic.ImageField<never>;
}

/**
 * Primary content in *SummitHighlight → Default → Primary*
 */
export interface SummitHighlightSliceDefaultPrimary {
  /**
   * title field in *SummitHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * title2 field in *SummitHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title2: prismic.RichTextField;

  /**
   * view all field in *SummitHighlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.view_all
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  view_all: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * item field in *SummitHighlight → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: summit_highlight.default.primary.item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  item: prismic.GroupField<
    Simplify<SummitHighlightSliceDefaultPrimaryItemItem>
  >;
}

/**
 * Default variation for SummitHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SummitHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SummitHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SummitHighlight*
 */
type SummitHighlightSliceVariation = SummitHighlightSliceDefault;

/**
 * SummitHighlight Shared Slice
 *
 * - **API ID**: `summit_highlight`
 * - **Description**: SummitHighlight
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SummitHighlightSlice = prismic.SharedSlice<
  "summit_highlight",
  SummitHighlightSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutpageDocument,
      AboutpageDocumentData,
      AboutpageDocumentDataSlicesSlice,
      CoalisionDocument,
      CoalisionDocumentData,
      CoalisionDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutHeroSlice,
      AboutHeroSliceDefaultPrimary,
      AboutHeroSliceVariation,
      AboutHeroSliceDefault,
      CoalisionHeroSlice,
      CoalisionHeroSliceDefaultPrimary,
      CoalisionHeroSliceVariation,
      CoalisionHeroSliceDefault,
      ExecutivesSlice,
      ExecutivesSliceDefaultPrimaryItemsItem,
      ExecutivesSliceDefaultPrimaryCountryRepsItem,
      ExecutivesSliceDefaultPrimaryStateRepsItem,
      ExecutivesSliceDefaultPrimary,
      ExecutivesSliceVariation,
      ExecutivesSliceDefault,
      HistorySlice,
      HistorySliceDefaultPrimaryItemsItem,
      HistorySliceDefaultPrimary,
      HistorySliceVariation,
      HistorySliceDefault,
      HomePageAboutSlice,
      HomePageAboutSliceDefaultPrimary,
      HomePageAboutSliceVariation,
      HomePageAboutSliceDefault,
      HomePageHeroSlice,
      HomePageHeroSliceDefaultPrimary,
      HomePageHeroSliceVariation,
      HomePageHeroSliceDefault,
      HowWeWorkSlice,
      HowWeWorkSliceDefaultPrimary,
      HowWeWorkSliceVariation,
      HowWeWorkSliceDefault,
      ImpactSlice,
      ImpactSliceDefaultPrimary,
      ImpactSliceVariation,
      ImpactSliceDefault,
      MagnifyOurVoicesSlice,
      MagnifyOurVoicesSliceDefaultPrimary,
      MagnifyOurVoicesSliceVariation,
      MagnifyOurVoicesSliceDefault,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
      SummitHighlightSlice,
      SummitHighlightSliceDefaultPrimaryItemItem,
      SummitHighlightSliceDefaultPrimary,
      SummitHighlightSliceVariation,
      SummitHighlightSliceDefault,
    };
  }
}
