// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | HowWeWorkSlice
  | ImpactSlice
  | HomePageAboutSlice
  | HomePageHeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *HomePageAbout → Default → Primary*
 */
export interface HomePageAboutSliceDefaultPrimary {
  /**
   * image field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * text field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * header text field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.header_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  header_text: prismic.RichTextField;

  /**
   * see more field in *HomePageAbout → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_about.default.primary.see_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  see_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HomePageAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomePageAboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomePageAbout*
 */
type HomePageAboutSliceVariation = HomePageAboutSliceDefault;

/**
 * HomePageAbout Shared Slice
 *
 * - **API ID**: `home_page_about`
 * - **Description**: HomePageAbout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageAboutSlice = prismic.SharedSlice<
  "home_page_about",
  HomePageAboutSliceVariation
>;

/**
 * Primary content in *HomePageHero → Default → Primary*
 */
export interface HomePageHeroSliceDefaultPrimary {
  /**
   * theme field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Theme
   * - **API ID Path**: home_page_hero.default.primary.theme
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  theme: prismic.KeyTextField;

  /**
   * hero text field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: From Representation To Protection
   * - **API ID Path**: home_page_hero.default.primary.hero_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_text: prismic.RichTextField;

  /**
   * primary button field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Register for Event
   * - **API ID Path**: home_page_hero.default.primary.primary_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * secondary burron field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Become an Event Partner
   * - **API ID Path**: home_page_hero.default.primary.secondary_burron
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_burron: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * tertiary button field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Find Out More
   * - **API ID Path**: home_page_hero.default.primary.tertiary_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  tertiary_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * hero image field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * sub image 1 field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.sub_image_1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sub_image_1: prismic.ImageField<never>;

  /**
   * sub image 2 field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.sub_image_2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sub_image_2: prismic.ImageField<never>;

  /**
   * even and campaign field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.even_and_campaign
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  even_and_campaign: prismic.RichTextField;

  /**
   * policy advocay field in *HomePageHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_hero.default.primary.policy_advocay
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  policy_advocay: prismic.RichTextField;
}

/**
 * Default variation for HomePageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomePageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomePageHero*
 */
type HomePageHeroSliceVariation = HomePageHeroSliceDefault;

/**
 * HomePageHero Shared Slice
 *
 * - **API ID**: `home_page_hero`
 * - **Description**: HomePageHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageHeroSlice = prismic.SharedSlice<
  "home_page_hero",
  HomePageHeroSliceVariation
>;

/**
 * Primary content in *HowWeWork → Default → Primary*
 */
export interface HowWeWorkSliceDefaultPrimary {
  /**
   * title field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * image1 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image3: prismic.ImageField<never>;

  /**
   * image4 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image4: prismic.ImageField<never>;

  /**
   * image5 field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image5
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image5: prismic.ImageField<never>;

  /**
   * image1 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image1_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image1_text: prismic.KeyTextField;

  /**
   * image2 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image2_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image2_text: prismic.KeyTextField;

  /**
   * image3 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image3_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image3_text: prismic.KeyTextField;

  /**
   * image4 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image4_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image4_text: prismic.KeyTextField;

  /**
   * image5 text field in *HowWeWork → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_work.default.primary.image5_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image5_text: prismic.KeyTextField;
}

/**
 * Default variation for HowWeWork Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HowWeWorkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowWeWorkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HowWeWork*
 */
type HowWeWorkSliceVariation = HowWeWorkSliceDefault;

/**
 * HowWeWork Shared Slice
 *
 * - **API ID**: `how_we_work`
 * - **Description**: HowWeWork
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HowWeWorkSlice = prismic.SharedSlice<
  "how_we_work",
  HowWeWorkSliceVariation
>;

/**
 * Primary content in *Impact → Default → Primary*
 */
export interface ImpactSliceDefaultPrimary {
  /**
   * title field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * productivity text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.productivity_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  productivity_text: prismic.RichTextField;

  /**
   * productivity vlaue field in *Impact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.productivity_vlaue
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  productivity_vlaue: prismic.NumberField;

  /**
   * investment text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.investment_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  investment_text: prismic.RichTextField;

  /**
   * investement value field in *Impact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.investement_value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  investement_value: prismic.NumberField;

  /**
   * customer text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.customer_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  customer_text: prismic.RichTextField;

  /**
   * customer value field in *Impact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.customer_value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  customer_value: prismic.NumberField;

  /**
   * review text field in *Impact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.review_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review_text: prismic.RichTextField;

  /**
   * review value field in *Impact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: impact.default.primary.review_value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  review_value: prismic.NumberField;
}

/**
 * Default variation for Impact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImpactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Impact*
 */
type ImpactSliceVariation = ImpactSliceDefault;

/**
 * Impact Shared Slice
 *
 * - **API ID**: `impact`
 * - **Description**: Impact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactSlice = prismic.SharedSlice<"impact", ImpactSliceVariation>;

/**
 * Primary content in *PageHeader → Default → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * wca logo field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.wca_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  wca_logo: prismic.ImageField<never>;

  /**
   * text field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: WCA SUMMIT OCTOBER 2025 (KIGALI, RWANDA)
   * - **API ID Path**: page_header.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * hours field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 22
   * - **API ID Path**: page_header.default.primary.hours
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  hours: prismic.NumberField;

  /**
   * minute field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 59
   * - **API ID Path**: page_header.default.primary.minute
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  minute: prismic.NumberField;

  /**
   * seconds field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 22
   * - **API ID Path**: page_header.default.primary.seconds_value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  seconds_value: prismic.NumberField;

  /**
   * days field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 56
   * - **API ID Path**: page_header.default.primary.days
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  days: prismic.NumberField;
}

/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHeader*
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;

/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HomePageAboutSlice,
      HomePageAboutSliceDefaultPrimary,
      HomePageAboutSliceVariation,
      HomePageAboutSliceDefault,
      HomePageHeroSlice,
      HomePageHeroSliceDefaultPrimary,
      HomePageHeroSliceVariation,
      HomePageHeroSliceDefault,
      HowWeWorkSlice,
      HowWeWorkSliceDefaultPrimary,
      HowWeWorkSliceVariation,
      HowWeWorkSliceDefault,
      ImpactSlice,
      ImpactSliceDefaultPrimary,
      ImpactSliceVariation,
      ImpactSliceDefault,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
    };
  }
}
