// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_hero: dynamic(() => import("./AboutHero")),
  coalision_hero: dynamic(() => import("./CoalisionHero")),
  executives: dynamic(() => import("./Teams")),
  history: dynamic(() => import("./History")),
  home_page_about: dynamic(() => import("./HomePageAbout")),
  home_page_hero: dynamic(() => import("./HomePageHero")),
  how_we_work: dynamic(() => import("./HowWeWork")),
  impact: dynamic(() => import("./Impact")),
  magnify_our_voices: dynamic(() => import("./MagnifyOurVoices")),
  page_header: dynamic(() => import("./PageHeader")),
  summit_highlight: dynamic(() => import("./SummitHighlight")),
};
