// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  home_page_about: dynamic(() => import("./HomePageAbout")),
  home_page_hero: dynamic(() => import("./HomePageHero")),
  how_we_work: dynamic(() => import("./HowWeWork")),
  impact: dynamic(() => import("./Impact")),
  page_header: dynamic(() => import("./PageHeader")),
};
