import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createClient } from "@/prismicio";
import { type Content } from "@prismicio/client";
import { PageHeader } from "@/components/PageHeader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();
  
  // Fetch homepage to get the PageHeader slice data
  const homepage = await client.getSingle("homepage").catch(() => null);
  
  // Find the PageHeader slice in the homepage slices
  const headerSlice = homepage?.data.slices?.find(
    (slice: any) => slice.slice_type === "page_header"
  ) as Content.PageHeaderSlice | undefined;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {headerSlice?.primary && (
          <PageHeader
            logo={headerSlice.primary.wca_logo}
            text={headerSlice.primary.text || undefined}
            days={headerSlice.primary.days || undefined}
            hours={headerSlice.primary.hours || undefined}
            minute={headerSlice.primary.minute || undefined}
            seconds_value={headerSlice.primary.seconds_value || undefined}
          />
        )}
        {children}
      </body>
    </html>
  );
}
