import type { Metadata } from "next";
import { Josefin_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import PageHeaderComp from "@/components/page-header";
import Footer from "@/components/footer";
import NextTopLoader from 'nextjs-toploader';

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} ${playfairDisplay.variable} antialiased`}
        suppressHydrationWarning
      >
        <NextTopLoader color="green" />
        <PageHeaderComp />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
